build_name           = "pfsense"
vm_id                = 905
vm_name              = "pfsense-ce-2-6-0"
iso_file             = "pfSense-CE-2.6.0.iso"
template_description = "Firewall pfSense template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."
